'use strict';

module.exports = [
    'src/lib/leaflet.control.panoramas/lib/mapillary/mvt.js',
    'src/lib/leaflet.control.panoramas/lib/mapillary/mapillary-coverage-layer.js',
    'src/lib/leaflet.control.panoramas/lib/mapillary/index.js',
    // 'src/lib/leaflet.control.panoramas/lib/mapillary/vector_tile_pb.js',
    'src/lib/leaflet.control.panoramas/lib/mapillary/mapillary-loader.js',
    'src/lib/leaflet.control.panoramas/lib/mapycz/apiLoader.js',
    'src/lib/leaflet.control.panoramas/lib/mapycz/index.js',
    'src/lib/leaflet.control.panoramas/lib/google/index.js',
    'src/lib/leaflet.control.panoramas/lib/wikimedia/index.js',
    'src/lib/leaflet.control.panoramas/lib/wikimedia/coverage-layer.js',
    'src/lib/leaflet.control.panoramas/lib/common/index.js',
    'src/lib/leaflet.control.panoramas/index.js',
    'src/lib/leaflet.polyline-edit/index.js',
    'src/lib/leaflet.control.layers.adaptive-height/index.js',
    // 'src/lib/leaflet.control.external-maps/index.js',
    'src/lib/leaflet.placemark/index.js',
    'src/lib/leaflet.layer.geojson-ajax/index.js',
    'src/lib/leaflet.layer.geocaching-su/index.js',
    'src/lib/file-read/index.js',
    'src/lib/CORSProxy/index.js',
    'src/lib/leaflet.polyline-measure/index.js',
    'src/lib/leaflet.control.coordinates/index.js',
    'src/lib/leaflet.control.coordinates/formats.js',
    'src/lib/tiled-data-loader/index.js',
    // 'src/lib/anyElementResizeEvent/index.js',
    'src/lib/leaflet.layer.google/index.js',
    'src/lib/leaflet.control.jnx/jnx-maker.js',
    'src/lib/leaflet.control.jnx/jnx-encoder.js',
    'src/lib/leaflet.control.jnx/binary-stream.js',
    'src/lib/leaflet.control.jnx/selector.js',
    'src/lib/leaflet.control.jnx/index.js',
    'src/lib/leaflet.control.jnx/hash-state.js',
    'src/lib/leaflet.control.layers.hotkeys/index.js',
    'src/lib/leaflet.layer.yandex/index.js',
    'src/lib/leaflet.control.commons/index.js',
    'src/lib/leaflet.lineutil.simplifyLatLngs/index.js',
    'src/lib/cache/index.js',
    'src/lib/xhr-promise/index.js',
    'src/lib/leaflet.fixes/fixWorldCopyJump.js',
    'src/lib/leaflet.fixes/index.js',
    'src/lib/leaflet.control.printPages/control.js',
    'src/lib/leaflet.control.printPages/decorations.js',
    'src/lib/leaflet.control.printPages/pdf.js',
    'src/lib/leaflet.control.printPages/decoration.grid.js',
    'src/lib/leaflet.control.printPages/decoration.scale.js',
    'src/lib/leaflet.control.printPages/map-render.js',
    'src/lib/leaflet.control.printPages/decoration.magnetic-meridians.js',
    'src/lib/leaflet.control.printPages/pageFeature.js',
    'src/lib/leaflet.control.layers.top-row/index.js',
    'src/lib/clipboardCopy/index.js',
    'src/lib/leaflet.hashState/hashState.js',
    'src/lib/leaflet.hashState/Leaflet.Control.Layers.js',
    'src/lib/leaflet.hashState/Leaflet.Map.js',
    'src/lib/leaflet.hashState/leaflet.hashState.js',
    // 'src/lib/leaflet.map.sidebars/index.js',
    'src/lib/leaflet.control.zoom-display/index.js',
    'src/lib/knockout.component.progress/progress.js',
    'src/lib/contextmenu/index.js',
    'src/lib/leaflet.layer.soviet-topomaps-grid/index.js',
    'src/lib/leaflet.layer.wikimapia/wm-utils.js',
    'src/lib/leaflet.layer.wikimapia/index.js',
    'src/lib/leaflet.layer.wikimapia/wikimapia-loader.js',
    'src/lib/leaflet.control.track-list/lib/meridian180.js',
    'src/lib/leaflet.control.track-list/lib/services/movescount.js',
    'src/lib/leaflet.control.track-list/lib/services/simpleService.js',
    'src/lib/leaflet.control.track-list/lib/services/sportstracker.js',
    'src/lib/leaflet.control.track-list/lib/services/nakarte/index.js',
    'src/lib/leaflet.control.track-list/lib/services/nakarte/loadTracksFromJson.js',
    'src/lib/leaflet.control.track-list/lib/services/urlEncode.js',
    'src/lib/leaflet.control.track-list/lib/services/baseService.js',
    'src/lib/leaflet.control.track-list/lib/services/strava.js',
    'src/lib/leaflet.control.track-list/lib/services/endomondo.js',
    'src/lib/leaflet.control.track-list/lib/services/index.js',
    'src/lib/leaflet.control.track-list/lib/services/garmin.js',
    'src/lib/leaflet.control.track-list/lib/services/tracedetrail.js',
    'src/lib/leaflet.control.track-list/lib/services/gpslib.js',
    'src/lib/leaflet.control.track-list/lib/services/openstreetmapRu.js',
    'src/lib/leaflet.control.track-list/lib/services/wikiloc.js',
    'src/lib/leaflet.control.track-list/lib/services/etomesto.js',
    'src/lib/leaflet.control.track-list/lib/services/yandex.js',
    'src/lib/leaflet.control.track-list/lib/services/osm.js',
    'src/lib/leaflet.control.track-list/lib/services/gpsies.js',
    'src/lib/leaflet.control.track-list/lib/parsers/jsInflate.js',
    'src/lib/leaflet.control.track-list/lib/parsers/kml.js',
    // 'src/lib/leaflet.control.track-list/lib/parsers/nktk_pb.js',
    'src/lib/leaflet.control.track-list/lib/parsers/nktk.js',
    'src/lib/leaflet.control.track-list/lib/parsers/gpx.js',
    'src/lib/leaflet.control.track-list/lib/parsers/index.js',
    'src/lib/leaflet.control.track-list/lib/parsers/ozi.js',
    'src/lib/leaflet.control.track-list/lib/parsers/zip.js',
    'src/lib/leaflet.control.track-list/lib/parsers/codePages.js',
    'src/lib/leaflet.control.track-list/lib/parsers/urlSafeBase64.js',
    'src/lib/leaflet.control.track-list/lib/parsers/xmlUtils.js',
    'src/lib/leaflet.control.track-list/lib/loadFromUrl.js',
    'src/lib/leaflet.control.track-list/lib/parseGeoFile.js',
    'src/lib/leaflet.control.track-list/lib/geo_file_exporters.js',
    'src/lib/leaflet.control.track-list/track-list.localstorage.js',
    'src/lib/leaflet.control.track-list/control-ruler.js',
    'src/lib/leaflet.control.track-list/track-list.hash-state.js',
    'src/lib/leaflet.control.track-list/track-list.js',
    // 'src/lib/leaflet.control.search/index.js',
    // 'src/lib/leaflet.control.search/providers/coordinates.js',
    // 'src/lib/leaflet.control.search/providers/remoteBase.js',
    // 'src/lib/leaflet.control.search/providers/index.js',
    // 'src/lib/leaflet.control.search/providers/mapycz/index.js',
    // 'src/lib/leaflet.control.search/providers/photon.js',
    // 'src/lib/leaflet.control.search/providers/links.js',
    'src/lib/leaflet.layer.canvasMarkers/index.js',
    'src/lib/notifications/index.js',
    'src/lib/binary-strings/index.js',
    'src/lib/safe-localstorage/index.js',
    'src/lib/leaflet.events.drag/index.js',
    'src/lib/magnetic-declination/index.js',
    'src/lib/leaflet.control.caption/index.js',
    'src/lib/leaflet.control.azimuth/index.js',
    'src/lib/leaflet.control.layers.minimize/index.js',
    'src/lib/stripBom/index.js',
    'src/lib/leaflet.control.layers.events/index.js',
    'src/lib/leaflet.layer.rasterize/CanvasMarkers.js',
    'src/lib/leaflet.layer.rasterize/imgFromDataString.js',
    'src/lib/leaflet.layer.rasterize/WestraPasses.js',
    'src/lib/leaflet.layer.rasterize/index.js',
    'src/lib/leaflet.layer.rasterize/TileLayer.js',
    'src/lib/leaflet.layer.rasterize/Google.js',
    'src/lib/leaflet.layer.rasterize/MeasuredLine.js',
    'src/lib/leaflet.layer.rasterize/Bing.js',
    'src/lib/leaflet.layer.rasterize/Yandex.js',
    'src/lib/leaflet.layer.rasterize/RetinaTileLayer.js',
    'src/lib/leaflet.layer.bing/dates.js',
    'src/lib/leaflet.layer.bing/index.js',
    'src/lib/logging/index.js',
    'src/lib/iconFromBackgroundImage/index.js',
    'src/lib/leaflet.controls.raise-on-focus/index.js',
    'src/lib/leaflet.control.elevation-profile/index.js',
    'src/lib/leaflet.control.layers.configure/index.js',
    'src/lib/leaflet.control.layers.configure/customLayer.js',
    'src/lib/leaflet.control.locate/index.js',
    'src/lib/leaflet.layer.westraPasses/index.js',
    'src/lib/leaflet.layer.westraPasses/westraPassesMarkers.js',
    'src/lib/elevations/index.js',
    'src/lib/popup-window/index.js',
    'src/lib/googleMapsApi/index.js',
    // 'src/vendored/mapbbcode/FunctionButton.js',
    // 'src/vendored/github.com/augustl/js-unzip/js-unzip.js',
    // 'src/vendored/github.com/eligrey/FileSaver.js',
    // 'src/vendored/github.com/bbecquet/Leaflet.RotatedMarker/leaflet.rotatedMarker.js',
    'src/config.js',
    'src/index.js',
    'src/secrets.js',
    'src/App.js',
    'src/layers.js',
];
